export const DEFAULT_DURATION = 0.3;
export const DEFAULT_DELAY = 0.15;
export const MAX_ITEM_IN_STACK = 5;
export const MAX_STACK_ANIMATION_DURATION = ((MAX_ITEM_IN_STACK * DEFAULT_DELAY) + DEFAULT_DURATION) * 500;